# Generated by Django 4.2.11 on 2024-06-06 13:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAIAssistantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_model', models.CharField(choices=[('gpt-3.5-turbo-0125', 'gpt-3.5-turbo-0125'), ('gpt-3.5-turbo', 'gpt-3.5-turbo'), ('gpt-3.5-turbo-1106', 'gpt-3.5-turbo-1106'), ('gpt-3.5-turbo-instruct', 'gpt-3.5-turbo-instruct')], max_length=100, verbose_name='Selected Model')),
                ('max_tokens', models.PositiveIntegerField(default=250, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4096)], verbose_name='Max Tokens')),
                ('temperature', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='Temperature')),
                ('top_p', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Top P')),
                ('frequency_penalty', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Frequency Penalty')),
                ('presence_penalty', models.FloatField(default=0.0, verbose_name='Presence Penalty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
