# Generated by Django 4.2.11 on 2024-06-09 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageAssistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openaiassistantsettings',
            name='frequency_penalty',
            field=models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Frequency Penalty'),
        ),
        migrations.AlterField(
            model_name='openaiassistantsettings',
            name='max_tokens',
            field=models.PositiveIntegerField(default=4096, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4096)], verbose_name='Max Tokens'),
        ),
        migrations.AlterField(
            model_name='openaiassistantsettings',
            name='presence_penalty',
            field=models.FloatField(default=0.5, verbose_name='Presence Penalty'),
        ),
        migrations.AlterField(
            model_name='openaiassistantsettings',
            name='temperature',
            field=models.FloatField(default=0.2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='Temperature'),
        ),
        migrations.AlterField(
            model_name='openaiassistantsettings',
            name='top_p',
            field=models.FloatField(default=1.1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Top P'),
        ),
    ]
