# Generated by Django 4.2.11 on 2024-07-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageBackgroundLooks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mybackgroundlooks',
            name='selected_image',
        ),
        migrations.AddField(
            model_name='mybackgroundlooks',
            name='selected_background',
            field=models.CharField(choices=[('black', 'Dark Background'), ('white', 'Bright Background')], default='white', max_length=100),
        ),
    ]
