# Generated by Django 4.2.11 on 2024-07-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageBackgroundLooks', '0002_remove_mybackgroundlooks_selected_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybackgroundlooks',
            name='selected_background',
            field=models.CharField(choices=[('black', 'Dark Background'), ('white', 'Bright Background'), ('lightgray', 'Light Gray Background'), ('lightblue', 'Light Blue Background'), ('beige', 'Beige Background'), ('lightgreen', 'Light Green Background'), ('lightcoral', 'Light Coral Background')], default='white', max_length=100),
        ),
    ]
