# Generated by Django 4.2.11 on 2024-07-10 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCareerSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_summary', models.TextField(blank=True, null=True, verbose_name='Career Summary')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_summary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Career Summary',
                'ordering': ['-created_at'],
            },
        ),
    ]
