# Generated by Django 4.2.11 on 2024-06-06 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageAccounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='stripe_customer_id',
        ),
    ]
