# Generated by Django 4.2.11 on 2024-06-14 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageJobApplications', '0004_applicationcredential'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='good_luck_message',
        ),
    ]
