# Generated by Django 4.2.11 on 2024-06-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageJobApplications', '0007_remove_resume_resume_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='resume_summary',
        ),
        migrations.AddField(
            model_name='resume',
            name='assistant_observation',
            field=models.TextField(blank=True, null=True, verbose_name='Assistant Observation'),
        ),
        migrations.AddField(
            model_name='resume',
            name='assistant_resume',
            field=models.TextField(blank=True, null=True, verbose_name='Assistant Resume'),
        ),
        migrations.AddField(
            model_name='resume',
            name='user_resume',
            field=models.TextField(blank=True, null=True, verbose_name='User Resume'),
        ),
    ]
