# Generated by Django 4.2.11 on 2024-06-20 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageJobApplications', '0008_remove_resume_resume_summary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='user_resume',
        ),
    ]
