# Generated by Django 4.2.11 on 2024-06-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageJobApplications', '0009_remove_resume_user_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverletter',
            name='assistant_observation',
            field=models.TextField(blank=True, max_length=3500, null=True, verbose_name='Assistant Observation'),
        ),
        migrations.AlterField(
            model_name='coverletter',
            name='letter',
            field=models.TextField(blank=True, max_length=3500, null=True, verbose_name='Cover Letter'),
        ),
    ]
