# Generated by Django 4.2.11 on 2024-06-21 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ManageJobApplications', '0010_coverletter_assistant_observation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewPreparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Preparation Title')),
                ('about_company', models.CharField(blank=True, max_length=255, null=True, verbose_name='About Company')),
                ('prep_question', models.TextField(blank=True, null=True, verbose_name='Preparation Question')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_preparations', to='ManageJobApplications.jobapplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_preparations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Interview Preparations',
                'ordering': ['-created_at'],
            },
        ),
    ]
