# Generated by Django 4.2.11 on 2024-06-21 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageJobApplications', '0011_interviewpreparation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewpreparation',
            old_name='prep_question',
            new_name='prep_questions',
        ),
    ]
