# Generated by Django 4.2.11 on 2024-06-24 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageJobApplications', '0012_rename_prep_question_interviewpreparation_prep_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='job_title',
        ),
    ]
