# Generated by Django 4.2.11 on 2024-07-04 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ManageJobApplications', '0015_alter_followupmessage_follow_up_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobProfileProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_summary', models.TextField(blank=True, null=True, verbose_name='Project Summary')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='ManageJobApplications.jobprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_profile_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Job Profile Projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
