# Generated by Django 4.2.11 on 2024-07-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageJobApplications', '0016_jobprofileproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofileproject',
            name='project_subject',
            field=models.CharField(blank=True, max_length=255, verbose_name='Job Title'),
        ),
    ]
