# Generated by Django 4.2.11 on 2024-07-21 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageSubscription', '0002_userpayment_refund_requested_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpayment',
            old_name='subscription_canceled',
            new_name='subscription_active',
        ),
    ]
